# STOA Platform — Status Page Configuration
# Powered by Upptime (https://upptime.js.org)

owner: stoa-platform
repo: status

sites:
  - name: API Gateway
    url: https://mcp.gostoa.dev/health
    icon: https://raw.githubusercontent.com/stoa-platform/status/master/assets/stoa-icon.svg

  - name: Control Plane API
    url: https://api.gostoa.dev/health/live
    icon: https://raw.githubusercontent.com/stoa-platform/status/master/assets/stoa-icon.svg

  - name: Console
    url: https://console.gostoa.dev
    icon: https://raw.githubusercontent.com/stoa-platform/status/master/assets/stoa-icon.svg

  - name: Developer Portal
    url: https://portal.gostoa.dev
    icon: https://raw.githubusercontent.com/stoa-platform/status/master/assets/stoa-icon.svg

  - name: Authentication (Keycloak)
    url: https://auth.gostoa.dev/realms/stoa/.well-known/openid-configuration
    icon: https://raw.githubusercontent.com/stoa-platform/status/master/assets/stoa-icon.svg

  - name: Documentation
    url: https://docs.gostoa.dev
    icon: https://raw.githubusercontent.com/stoa-platform/status/master/assets/stoa-icon.svg

  - name: Landing Page
    url: https://gostoa.dev
    icon: https://raw.githubusercontent.com/stoa-platform/status/master/assets/stoa-icon.svg

status-website:
  cname: status.gostoa.dev
  logoUrl: https://raw.githubusercontent.com/stoa-platform/status/master/assets/stoa-logo.svg
  favicon: https://raw.githubusercontent.com/stoa-platform/status/master/assets/stoa-icon.svg
  faviconSvg: https://raw.githubusercontent.com/stoa-platform/status/master/assets/stoa-icon.svg
  name: STOA Platform Status
  introTitle: "**STOA Platform** is the European Agent Gateway — AI-native API management, open source."
  introMessage: >
    This page provides real-time operational transparency for all STOA Cloud services.
    Uptime figures are observed metrics, not contractual commitments.
    [Visit STOA](https://gostoa.dev) | [Documentation](https://docs.gostoa.dev)
  navbar:
    - title: Status
      href: /
    - title: Documentation
      href: https://docs.gostoa.dev
    - title: GitHub
      href: https://github.com/stoa-platform
  theme: light

# Check every 5 minutes
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Commits
commitMessages:
  statusChange: "$EMOJI $NAME is $STATUS ($RESPONSE_TIME ms)"
  degradedPerformance: "$NAME has degraded performance ($RESPONSE_TIME ms)"
  scheduleDown: "$NAME is down (scheduled maintenance)"

# Skip initial README update to avoid empty history issues
skipDeleteIssues: true
